/**
 * js/restaurants.js
 * Raw restaurant dataset for Mom's 50th Birthday celebration.
 */

export const RESTAURANTS_RAW = [
  {
    id: 1,
    name: "Bombay House – Tempe",
    cuisine: "Indian",
    isBuffet: true,
    priceLevel: 1,
    priceDisplay: "~$15–$18 pp ($)",
    lat: 33.3783,
    lng: -111.9094,
    address: "1801 E Baseline Rd #104, Tempe, AZ 85283",
    rating: "4.6 ★",
    dishes: "Butter chicken, Tandoori chicken drumsticks, Coconut fish curry, Garlic naan.",
    menuUrl: "https://bombayhousetempe.com/",
    googleMapUrl: "https://maps.google.com/?q=Bombay+House+Tempe"
  },
  {
    id: 2,
    name: "Yama Sushi House – Chandler",
    cuisine: "Sushi",
    isBuffet: true,
    priceLevel: 2,
    priceDisplay: "~$25–$35 pp ($$)",
    lat: 33.3201,
    lng: -111.8622,
    address: "1175 W Ray Rd #1, Chandler, AZ 85224",
    rating: "4.5 ★",
    dishes: "All-You-Can-Eat sushi, sashimi, specialty rolls, gyoza, chicken teriyaki.",
    menuUrl: "https://yamasushihouse.com/",
    googleMapUrl: "https://maps.google.com/?q=Yama+Sushi+House+Chandler"
  },
  {
    id: 3,
    name: "Malee's Thai Bistro – Old Town",
    cuisine: "Thai",
    isBuffet: false,
    priceLevel: 2,
    priceDisplay: "~$20–$30 pp ($$)",
    lat: 33.4932,
    lng: -111.9287,
    address: "7131 E Main St, Scottsdale, AZ 85251",
    rating: "4.4 ★",
    dishes: "Evil Jungle Curry, Tom Yum Soup, Pad Thai, Pineapple Fried Rice.",
    menuUrl: "https://maleesonmain.com/",
    googleMapUrl: "https://maps.google.com/?q=Malees+Thai+Bistro+Scottsdale"
  },
  {
    id: 4,
    name: "SumoMaya – Scottsdale",
    cuisine: "Asian-Mexican Fusion",
    isBuffet: false,
    priceLevel: 3,
    priceDisplay: "~$45–$65 pp ($$$)",
    lat: 33.5338,
    lng: -111.9261,
    address: "6560 N Scottsdale Rd, Scottsdale, AZ 85253",
    rating: "4.5 ★",
    dishes: "Pork Belly Tacos, Korean BBQ Beef Tacos, Sushi Rolls, Churros with Salted Caramel.",
    menuUrl: "https://sumomaya.com/",
    googleMapUrl: "https://maps.google.com/?q=SumoMaya+Scottsdale"
  },
  {
    id: 5,
    name: "Bombay House – Scottsdale",
    cuisine: "Indian",
    isBuffet: true,
    priceLevel: 1,
    priceDisplay: "~$15–$18 pp ($)",
    lat: 33.5552,
    lng: -111.9095,
    address: "7001 N Scottsdale Rd, Scottsdale, AZ 85253",
    rating: "4.6 ★",
    dishes: "Chicken Tikka Masala, Lamb Korma, Saag Paneer, Fresh Tandoori Naan.",
    menuUrl: "https://bombayhousetempe.com/",
    googleMapUrl: "https://maps.google.com/?q=Bombay+House+Scottsdale"
  },
  {
    id: 7,
    name: "Yama Sushi House – Central Phoenix",
    cuisine: "Sushi",
    isBuffet: true,
    priceLevel: 2,
    priceDisplay: "~$25–$35 pp ($$)",
    lat: 33.5065,
    lng: -112.0738,
    address: "4750 N Central Ave, Phoenix, AZ 85012",
    rating: "4.5 ★",
    dishes: "All-You-Can-Eat sushi, specialty rolls, tempura, edamame.",
    menuUrl: "https://yamasushihouse.com/",
    googleMapUrl: "https://maps.google.com/?q=Yama+Sushi+House+Phoenix"
  },
  {
    id: 8,
    name: "Yama Sushi House – Scottsdale",
    cuisine: "Sushi",
    isBuffet: true,
    priceLevel: 2,
    priceDisplay: "~$25–$35 pp ($$)",
    lat: 33.5675,
    lng: -111.9168,
    address: "7704 E Doubletree Ranch Rd #150, Scottsdale, AZ 85258",
    rating: "4.6 ★",
    dishes: "All-You-Can-Eat sushi, nigiri, dragon rolls, gyoza.",
    menuUrl: "https://yamasushihouse.com/",
    googleMapUrl: "https://maps.google.com/?q=Yama+Sushi+House+Scottsdale"
  },
  {
    id: 9,
    name: "The Mexicano – Phoenix/PV",
    cuisine: "Mexican",
    isBuffet: false,
    priceLevel: 3,
    priceDisplay: "~$35–$50 pp ($$$)",
    lat: 33.5990,
    lng: -111.9790,
    address: "4801 E Cactus Rd, Phoenix, AZ 85254",
    rating: "4.4 ★",
    dishes: "3-Foot Piñata Guacamole, Birria Tacos, Sizzling Fajitas, Churro Cart.",
    menuUrl: "https://themexicano.com/",
    googleMapUrl: "https://maps.google.com/?q=The+Mexicano+Phoenix"
  },
  {
    id: 10,
    name: "Kasai Japanese Steakhouse – Scottsdale",
    cuisine: "Japanese / Teppanyaki",
    isBuffet: false,
    priceLevel: 3,
    priceDisplay: "~$40–$60 pp ($$$)",
    lat: 33.6169,
    lng: -111.9261,
    address: "14418 N Scottsdale Rd, Scottsdale, AZ 85254",
    rating: "4.6 ★",
    dishes: "Teppanyaki Flaming Shows, Filet Mignon, Lobster Tail, Fried Rice.",
    menuUrl: "https://kasaisteakhouse.com/",
    googleMapUrl: "https://maps.google.com/?q=Kasai+Scottsdale"
  },
  {
    id: 11,
    name: "Yama Sushi House – Union Hills",
    cuisine: "Sushi",
    isBuffet: true,
    priceLevel: 2,
    priceDisplay: "~$25–$35 pp ($$)",
    lat: 33.6552,
    lng: -112.0641,
    address: "1840 E Union Hills Dr, Phoenix, AZ 85024",
    rating: "4.5 ★",
    dishes: "All-You-Can-Eat sushi, rainbow rolls, teriyaki chicken, miso soup.",
    menuUrl: "https://yamasushihouse.com/",
    googleMapUrl: "https://maps.google.com/?q=Yama+Sushi+House+Union+Hills"
  },
  {
    id: 12,
    name: "Tandoori Times 2 – Glendale",
    cuisine: "Indian",
    isBuffet: true,
    priceLevel: 2,
    priceDisplay: "~$18–$22 pp ($$)",
    lat: 33.6393,
    lng: -112.1802,
    address: "6751 W Bell Rd, Glendale, AZ 85308",
    rating: "4.2 ★",
    dishes: "Lunch Buffet, Chicken Tikka, Malai Kofta, Garlic Naan.",
    menuUrl: "http://tandooritimes.com/",
    googleMapUrl: "https://maps.google.com/?q=Tandoori+Times+Glendale"
  },
  {
    id: 13,
    name: "Kasai Japanese Steakhouse – Peoria",
    cuisine: "Japanese / Teppanyaki",
    isBuffet: false,
    priceLevel: 3,
    priceDisplay: "~$40–$60 pp ($$$)",
    lat: 33.5528,
    lng: -112.2705,
    address: "9824 W Northern Ave, Peoria, AZ 85345",
    rating: "4.6 ★",
    dishes: "Teppanyaki Tableside Show, Steak & Shrimp, Fireball Cocktails.",
    menuUrl: "https://kasaisteakhouse.com/",
    googleMapUrl: "https://maps.google.com/?q=Kasai+Peoria"
  },
  {
    id: 14,
    name: "Yama Sushi House – Peoria",
    cuisine: "Sushi",
    isBuffet: true,
    priceLevel: 2,
    priceDisplay: "~$25–$35 pp ($$)",
    lat: 33.5528,
    lng: -112.2705,
    address: "9780 W Northern Ave, Peoria, AZ 85345",
    rating: "4.5 ★",
    dishes: "All-You-Can-Eat sushi, sashimi, specialty rolls.",
    menuUrl: "https://yamasushihouse.com/",
    googleMapUrl: "https://maps.google.com/?q=Yama+Sushi+House+Peoria"
  }
];
